name: Deploy dist Folder

on:
  push:
    branches:
      - main  # 监听 main 分支的推送事件

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
    # 1. Checkout the main branch
    - name: Checkout main branch
      uses: actions/checkout@v3

    # 2. Set Git user name and email
    - name: Set Git identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # 3. Checkout deploy branch
    - name: Checkout deploy branch
      run: |
        git fetch
        git checkout deploy || git checkout -b deploy  # 如果 deploy 分支不存在，则创建它

    # 4. 清理 deploy 分支（删除所有文件）
    - name: Remove all files in deploy branch
      run: |
        git rm -rf .  # 删除 deploy 分支中的所有文件

    # 5. 检出 main 分支中的 dist 目录（包括 dist 目录本身）
    - name: Checkout dist directory
      run: |
        git checkout main -- dist  # 检出整个 dist 目录

    # 6. 提交并推送 deploy 分支
    - name: Commit and push changes
      run: |
        git add .  # 添加 dist 目录及其内容
        git commit -m "Sync dist directory contents"
        git push origin deploy
