name: Deploy dist Folder

on:
  push:
    branches:
      - main  # 监听 main 分支的推送事件

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
    # 1. Checkout the main branch
    - name: Checkout main branch
      uses: actions/checkout@v3

    # 2. Checkout deploy branch
    - name: Checkout deploy branch
      run: |
        git fetch
        git checkout deploy || git checkout -b deploy  # 如果 deploy 分支不存在，则创建它

    # 3. 清理 deploy 分支（删除非 dist 内容）
    - name: Remove non-dist files from deploy branch
      run: |
        # 删除所有文件但保留 dist 文件夹内容
        git rm -rf .
        git checkout main -- dist/*  # 仅从 main 分支拉取 dist 文件夹中的文件，不拉取 dist 目录

    # 4. 提交并推送 deploy 分支
    - name: Commit and push changes
      run: |
        git add .  # 添加 dist 文件夹中的所有文件
        git commit -m "Sync dist folder contents (without dist directory)"
        git push origin deploy
